import os
import pandas as pd
import yaml
from typing import List, Dict, Any
from src.utils.logger import setup_logger
from src.features.team_strength import TeamStrengthFeatures
from src.features.recent_form import RecentFormFeatures
from src.features.head_to_head import HeadToHeadFeatures
from src.features.attack_features import AttackFeatures
from src.features.defence_features import DefenceFeatures
from src.features.tournament_features import TournamentFeatures
from src.features.context_features import ContextFeatures

logger = setup_logger("feature_store")

class FeatureStore:
    def __init__(self, config_path: str = "configs/data_config.yaml"):
        with open(config_path, "r") as f:
            self.config = yaml.safe_load(f)
        self.generators = [
            ("team_strength", TeamStrengthFeatures()),
            ("recent_form", RecentFormFeatures()),
            ("head_to_head", HeadToHeadFeatures()),
            ("attack", AttackFeatures()),
            ("defence", DefenceFeatures()),
            ("tournament", TournamentFeatures(config_path=config_path)),
            ("context", ContextFeatures())
        ]

    def build_features(self, master_df: pd.DataFrame) -> pd.DataFrame:
        """Runs all feature generators and merges their outputs."""
        logger.info(f"Building features from master dataset of shape {master_df.shape}...")
        
        # Start with the base metadata and target labels
        base_cols = ['date', 'home_team', 'away_team', 'home_score', 'away_score', 'tournament', 'city', 'country']
        feature_df = master_df[base_cols].copy()
        
        # Keep track of which features are generated by which family
        self.feature_families = {}
        
        # We will sequentially run each generator and join the features.
        # Note: some generators depend on features from previous generators (e.g. AttackFeatures depends on RecentFormFeatures).
        # Therefore, we run them in the order defined in self.generators.
        working_df = master_df.copy()
        
        for name, generator in self.generators:
            logger.info(f"Running feature generator: {name}")
            try:
                gen_features = generator.generate(working_df)
                logger.info(f"Generated {len(gen_features.columns)} features for family '{name}'")
                
                # Update working_df with the new features so subsequent generators can use them
                for col in gen_features.columns:
                    working_df[col] = gen_features[col]
                    feature_df[col] = gen_features[col]
                    
                self.feature_families[name] = list(gen_features.columns)
            except Exception as e:
                logger.error(f"Error in feature generator '{name}': {e}", exc_info=True)
                raise e
                
        logger.info(f"Completed feature building. Final feature store shape: {feature_df.shape}")
        return feature_df

    def save_feature_store(self, df: pd.DataFrame, version: str = "v1.0") -> Dict[str, str]:
        """Saves the feature store to Parquet and CSV formats."""
        out_dir = self.config["processed_paths"]["processed_directory"]
        os.makedirs(out_dir, exist_ok=True)
        
        parquet_path = os.path.join(out_dir, f"feature_store_{version}.parquet")
        csv_path = os.path.join(out_dir, f"feature_store_{version}.csv")
        
        # Also save to the unversioned canonical path
        canonical_parquet_path = os.path.join(out_dir, "feature_store.parquet")
        canonical_csv_path = os.path.join(out_dir, "feature_store.csv")
        
        logger.info(f"Saving versioned feature store ({version}) to {parquet_path}...")
        df.to_parquet(parquet_path, index=False)
        df.to_csv(csv_path, index=False)
        
        df.to_parquet(canonical_parquet_path, index=False)
        df.to_csv(canonical_csv_path, index=False)
        
        logger.info("Feature store saved successfully.")
        return {
            "versioned_parquet": parquet_path,
            "versioned_csv": csv_path,
            "canonical_parquet": canonical_parquet_path,
            "canonical_csv": canonical_csv_path
        }
